version: "3.8"

services:
  # your development container
  app:
    image: mcr.microsoft.com/devcontainers/python:3.12
    container_name: app
    command: sleep infinity           # VS Code will attach its own shell
    volumes:
      - .:/workspace:cached
    depends_on:
      - db
    environment:                      # convenient psql defaults
      PGHOST: db
      PGUSER: dev
      PGPASSWORD: devpass
      PGDATABASE: secure_db
      PGPORT: 5432

  # Postgres service
  db:
    image: postgres:16-alpine
    container_name: pg_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: secure_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
