version: "3.8"

services:
  # ← this is the container you’ll work in
  app:
    image: mcr.microsoft.com/devcontainers/python:3.12
    volumes:
      - ..:/workspace:cached          # mount repo
    command: sleep infinity           # keep it running
    # forward the host Docker socket so `docker` works
    volumes_from:
      - dockersock
    networks:
      - backend

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: devdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend

  # helper to share the host’s Docker socket
  dockersock:
    image: alpine
    command: tail -f /dev/null
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # no need to expose this container
    networks:
      - backend

volumes:
  postgres-data:

networks:
  backend:
