services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    ports: ["5432:5432"]
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: secure_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
