services:
  db:
    image: postgres:16-alpine       # lightweight (~55 MB compressed)
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: secure_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U dev" ]
volumes:
  pgdata: